version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: social_media_db
    environment:
      POSTGRES_DB: social_media_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 00000000
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: social-media-api
    container_name: social-media-api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/social_media_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 00000000
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    ports:
      - "8000:8080"

volumes:
  postgres_data:

